# Generated by Django 5.1.3 on 2024-12-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('config', models.JSONField()),
                ('secret_config', models.JSONField()),
                ('type', models.IntegerField(choices=[(1, 'OpenAI'), (2, 'Ollama')])),
            ],
        ),
    ]
