# Generated by Django 5.1.3 on 2024-12-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0005_alter_chatmodel_secret_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='tokenizer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
