# Generated by Django 5.1.4 on 2024-12-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0006_chatmodel_tokenizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'OpenAI'), (2, 'Ollama'), (99, 'Fake')]),
        ),
    ]
