# Generated by Django 5.1.4 on 2024-12-17 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0007_alter_chatmodel_type'),
        ('threads', '0007_alter_threadmessage_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatModel',
            new_name='LanguageModel',
        ),
    ]
