# Generated by Django 5.1.4 on 2024-12-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0010_remove_languagemodel_secret_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingmodel',
            name='size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
