# Generated by Django 5.1.4 on 2025-01-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0012_remove_embeddingmodel_secret_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingmodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'OpenAI'), (2, 'Ollama'), (3, 'Mistral'), (99, 'Fake')]),
        ),
        migrations.AlterField(
            model_name='languagemodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'OpenAI'), (2, 'Ollama'), (3, 'Mistral'), (99, 'Fake')]),
        ),
    ]
