services:
  core:
    image: cerebrix-core:latest
    container_name: cerebrix-core
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: /start.sh
    ports:
      - "8080:8080"
    volumes:
      - ./cerebrix:/app
    env_file:
      - .env
    network_mode: host
    # tty: true
    # stdin_open: true