services:
  core:
    image: cerebrix-core:latest
    container_name: cerebrix-core
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: /start.sh
    ports:
      - "8000:8000"
    volumes:
      - ./cerebrix:/app
    env_file:
      - .env
    tty: true
    stdin_open: true
    depends_on:
      - redis
    network_mode: host

  redis:
    container_name: "c51pgb-redis"
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    network_mode: host

  worker:
    image: cerebrix-core:latest
    container_name: cerebrix-worker 
    command: celery -A cerebrix worker -l INFO
    volumes:
      - ./cerebrix:/app
    env_file:
      - .env
    network_mode: host
    restart: unless-stopped
    depends_on:
      - core
      - redis
