# Generated by Django 5.1.3 on 2024-12-05 06:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0004_chatmodel_context_window_alter_chatmodel_created_by_and_more'),
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThreadBacked',
            new_name='ThreadBackend',
        ),
    ]
