# Generated by Django 5.1.3 on 2024-12-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_rename_threadbacked_threadbackend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='summary_tokens',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='tokens',
        ),
    ]
