# Generated by Django 5.1.4 on 2024-12-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_remove_thread_summary_tokens_remove_thread_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadmessage',
            old_name='tokens',
            new_name='content_tokens',
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
