# Generated by Django 5.1.4 on 2024-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_rename_tokens_threadmessage_content_tokens_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='threadbackend',
            name='memory_size',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='threadbackend',
            name='memory_type',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('simple', 'Simple')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='threadmessage',
            name='role',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User'), ('ai', 'Assistant'), ('summarizer', 'Summarizer')], max_length=20),
        ),
    ]
