# Generated by Django 5.1.4 on 2024-12-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_alter_threadmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadbackend',
            name='short_term_memory_size',
            field=models.SmallIntegerField(default=20),
        ),
    ]
