# Generated by Django 5.1.4 on 2024-12-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_threadbackend_short_term_memory_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmessage',
            name='role',
            field=models.CharField(choices=[('system', 'System'), ('human', 'Human'), ('ai', 'Assistant'), ('summarizer', 'Summarizer')], max_length=20),
        ),
    ]
