# Generated by Django 5.1.4 on 2024-12-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_alter_threadmessage_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='summary',
        ),
    ]
