# Generated by Django 5.1.4 on 2024-12-20 11:58

import django.db.models.deletion
import django.utils.timezone
import encrypted_json_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0011_embeddingmodel_size'),
        ('vector_stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorstorebackend',
            name='config',
            field=encrypted_json_fields.fields.EncryptedJSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vectorstorebackend',
            name='type',
            field=models.IntegerField(choices=[(1, 'Qdrant')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VectorStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=255)),
                ('metric', models.IntegerField(blank=True, choices=[(1, 'Cosine'), (2, 'Euclidean'), (3, 'Dot Product'), (4, 'Manhattan')], default=1, editable=False, null=True)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vector_stores.vectorstorebackend')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('embedding_model', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aimodels.embeddingmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
