# Generated by Django 5.1.4 on 2025-01-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector_stores', '0003_document_vectordocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectordocument',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
