# Generated by Django 5.1.4 on 2025-01-09 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector_stores', '0004_vectordocument_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectordocument',
            name='embedding_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=None, null=True, size=None),
        ),
    ]
